# Acropolis SPO state module

[package]
name = "acropolis_module_spo_state"
version = "0.1.0"
edition = "2021"
authors = ["Alex Woods <alex.woods@iohk.io>"]
description = "SPO State Tracker"
license = "Apache-2.0"

[dependencies]
acropolis_common = { path = "../../common" }

caryatid_sdk = { workspace = true }

anyhow = { workspace = true }
config = { workspace = true }
dashmap = { workspace = true }
hex = { workspace = true }
imbl = { workspace = true }
rayon = "1.11.0"
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lib]
path = "src/spo_state.rs"
