# Acropolis architecture workspace root

[workspace]
members = [
    # Global message definitions
    "messages",

    # Modules
    "modules/genesis_bootstrapper",    # Genesis bootstrap UTXOs
    "modules/mithril_snapshot_fetcher",# Mithril snapshot fetcher
    "modules/upstream_chain_fetcher",  # Upstream chain fetcher
    "modules/block_unpacker",          # Block to transaction unpacker
    "modules/tx_unpacker",             # Tx to UTXO unpacker
    "modules/utxo_state",              # UTXO state

    # Process builds
    "processes/omnibus",               # All-inclusive omnibus process
]

resolver = "2"
