# Acropolis architecture workspace root

[workspace]
members = [
    # Global message definitions
    "messages",

    # Modules
    "modules/genesis_bootstrapper",    # Genesis bootstrap UTXOs
    "modules/miniprotocols",           # Mini-protocol multiplexer
    "modules/block_unpacker",          # Block to transaction unpacker
    "modules/tx_unpacker",             # Tx to UTXO unpacker
    "modules/ledger_state",            # Ledger state

    # Process builds
    "processes/omnibus",               # All-inclusive omnibus process
]

resolver = "2"
