# Acropolis architecture workspace root

[patch.crates-io]
caryatid_sdk = { path = "../caryatid/sdk" }
caryatid_module_clock = { path = "../caryatid/modules/clock" }
caryatid_module_rest_server = { path = "../caryatid/modules/rest_server" }
caryatid_module_spy = { path = "../caryatid/modules/spy" }

[workspace]
members = [
    # Global message and common definitions
    "common",

    # Modules
    "modules/genesis_bootstrapper",    # Genesis bootstrap UTXOs
    "modules/mithril_snapshot_fetcher",# Mithril snapshot fetcher
    "modules/upstream_chain_fetcher",  # Upstream chain fetcher
    "modules/block_unpacker",          # Block to transaction unpacker
    "modules/tx_unpacker",             # Tx to UTXO unpacker
    "modules/utxo_state",              # UTXO state
    "modules/spo_state",               # SPO state
    "modules/drep_state",              # DRep state
    "modules/governance_state",        # Governance state
    "modules/stake_delta_filter",      # Filters address deltas

    # Process builds
    "processes/omnibus",               # All-inclusive omnibus process
    "processes/replayer",              # All-inclusive process to replay messages
]

resolver = "2"
