# Top-level configuration for Acropolis omnibus process

[module.genesis-bootstrapper]

[module.miniprotocols]
sync-point = "origin"
node-address = "backbone.cardano.iog.io:3001"
magic-number = 764824073

[module.block-unpacker]

[module.tx-unpacker]

[module.ledger-state]

[module.clock]

[message-bus.external]
class = "rabbit-mq"
url = "amqp://127.0.0.1:5672/%2f"
exchange = "caryatid"

[message-bus.internal]
class = "in-memory"
workers = 10

# Message routing
[[message-router.route]]  # Everything is internal only
pattern = "#"
bus = "internal"
