{
 "title": "Cardano: Application metrics v1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cardano Last Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Slot Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Chain Density",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cardano_node_metrics_epoch_int", "legendFormat": "{{alias}}" },
    { "expr": "cardano_node_metrics_epoch_int", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Slot leading share (% of slots led)",
   "type": "timeseries",
   "description": "Calculated at a 1 hr averaging window",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(cardano_node_metrics_Forge_node_is_leader_int[1h])/rate(cardano_node_metrics_slotNum_int[1h])) ",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum((rate(cardano_node_metrics_Forge_node_is_leader_int[1h])/rate(cardano_node_metrics_slotNum_int[1h])) )",
     "legendFormat": "Total led slots"
    },
    {
     "expr": "(rate(cardano_node_metrics_Forge_node_is_leader_int[1h])/rate(cardano_node_metrics_slotNum_int[1h])) ",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum((rate(cardano_node_metrics_Forge_node_is_leader_int[1h])/rate(cardano_node_metrics_slotNum_int[1h])) )",
     "legendFormat": "Total led slots"
    }
   ]
  },
  {
   "title": "Rejected blocks since last restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int - cardano_node_metrics_Forge_adopted_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_Forge_forged_int - cardano_node_metrics_Forge_adopted_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Missed slots rate (slots/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_slotsMissedNum_int[1m])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano-ping P95 latency (ms) - last hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, cardano_ping_latency_ms[1h:1m])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "avg(quantile_over_time(0.95, cardano_ping_latency_ms{class=~\".*relay\"}[1h:1m]))",
     "legendFormat": "All relays"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(cardano_node_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "quantile(0.5, cardano_node_metrics_blockfetchclient_blocksize / on(alias,cpus) (cardano_node_protocol_maxBlockBodySize + cardano_node_protocol_maxBlockHeaderSize))",
     "legendFormat": "last"
    },
    {
     "expr": "avg(avg_over_time(cardano_node_metrics_blockfetchclient_blocksize{alias=~\"rel-.?-[1..2]\"}[15m]) / on(alias,cpus) (cardano_node_protocol_maxBlockBodySize{alias=~\"rel-.?-[1..2]\"} + cardano_node_protocol_maxBlockHeaderSize{alias=~\"rel-.?-[1..2]\"}))",
     "legendFormat": "15 min average"
    },
    {
     "expr": "avg(avg_over_time(cardano_node_metrics_blockfetchclient_blocksize{alias=~\"rel-.?-[1..2]\"}[4h]) / on(alias,cpus) (cardano_node_protocol_maxBlockBodySize{alias=~\"rel-.?-[1..2]\"} + cardano_node_protocol_maxBlockHeaderSize{alias=~\"rel-.?-[1..2]\"}))",
     "legendFormat": "4h average"
    },
    {
     "expr": "avg(avg_over_time(cardano_node_metrics_blockfetchclient_blocksize{alias=~\"rel-.?-[1..2]\"}[24h]) / on(alias,cpus) (cardano_node_protocol_maxBlockBodySize{alias=~\"rel-.?-[1..2]\"} + cardano_node_protocol_maxBlockHeaderSize{alias=~\"rel-.?-[1..2]\"}))",
     "legendFormat": "24h average"
    },
    {
     "expr": "avg(avg_over_time(cardano_node_metrics_blockfetchclient_blocksize{alias=~\"rel-.?-[1..2]\"}[7d]) / on(alias,cpus) (cardano_node_protocol_maxBlockBodySize{alias=~\"rel-.?-[1..2]\"} + cardano_node_protocol_maxBlockHeaderSize{alias=~\"rel-.?-[1..2]\"}))",
     "legendFormat": "7 days average"
    }
   ]
  },
  {
   "title": "Mempool Txs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(cardano_node_metrics_txsInMempool_int{alias=~\"rel-.?-[1..2]\"}[30m]))",
     "legendFormat": "30 min average"
    }
   ]
  },
  {
   "title": "KES Periods Remaining",
   "type": "timeseries",
   "description": "KES periods remaining",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_Forge_metrics_remainingKESPeriods_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Current KES Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cardano_node_Forge_metrics_currentKESPeriod_int)"
    },
    {
     "expr": "avg(cardano_node_metrics_currentKESPeriod_int)"
    }
   ]
  },
  {
   "title": "KES Time Remaining (Alternate Method)",
   "type": "timeseries",
   "description": "Secondary method of calculating the KES time remaining until expiration",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(cardano_node_genesis_slotLength * (cardano_node_genesis_slotsPerKESPeriod * ((cardano_node_decode_kesCreatedPeriod > -1) + cardano_node_genesis_maxKESEvolutions)) - on(alias,cpus) (cardano_node_genesis_slotLength * on(alias,cpus) cardano_node_metrics_slotNum_int))",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "(cardano_node_genesis_slotLength * (cardano_node_genesis_slotsPerKESPeriod * ((cardano_node_decode_kesCreatedPeriod > -1) + cardano_node_genesis_maxKESEvolutions)) - on(alias,cpus) (cardano_node_genesis_slotLength * on(alias,cpus) cardano_node_metrics_slotNum_int))",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1/rate(cardano_node_metrics_slotNum_int[600s])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "1/rate(cardano_node_metrics_slotNum_int[600s])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "KES Time Remaining Until Expiration",
   "type": "timeseries",
   "description": "KES time remaining",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cardano_node_Forge_metrics_remainingKESPeriods_int * on(alias,cpus) cardano_node_genesis_slotsPerKESPeriod * on(alias,cpus) cardano_node_genesis_slotLength",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int * on(alias,cpus) cardano_node_genesis_slotsPerKESPeriod * on(alias,cpus) cardano_node_genesis_slotLength",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "CPU Utilization (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Decentralization Parameter (d)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_protocol_decentralisationParam >= 0",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "timeseries",
   "description": "/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time()-node_boot_time_seconds)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Service Restarts Per Hour",
   "type": "graph",
   "description": "Shows how many times cardano related services have been restarted within a 1 hour lookback window",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(increase(node_systemd_unit_state{name=~\"cardano.*|byron.*|explorer.*\",state=\"active\"}[1h:10s])) > 0",
     "legendFormat": "{{alias}}-{{name}}"
    }
   ]
  },
  {
   "title": "Node Memory Free (%)",
   "type": "timeseries",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Memory Available (%)",
   "type": "timeseries",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Bandwidth (bps)",
   "type": "timeseries",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s])) * 8",
     "legendFormat": "Aggregate cluster ingress (received)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Aggregate cluster egress (transmit)"
    }
   ]
  },
  {
   "title": "Node peak memory allocated (from OS, in MBytes)",
   "type": "timeseries",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node max \"residency\" (amount of live data, MBytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Faucet (ADA)",
   "type": "timeseries",
   "description": "Remaining faucet funds in ADA",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_faucet_metrics_value_available / 1e6",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Bandwidth (bps)",
   "type": "timeseries",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}