#!/bin/bash
set -e
podman play kube /home/ubuntu/testnet-generation-tool/testnet/monitoring.yaml
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/1/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/1/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/1/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/1/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/1/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db1 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.1.socket --port 3001 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.1.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/2/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/2/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/2/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/2/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/2/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db2 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.2.socket --port 3002 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.2.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/3/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/3/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/3/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/3/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/3/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db3 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.3.socket --port 3003 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.3.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/4/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/4/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/4/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/4/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/4/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db4 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.4.socket --port 3004 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.4.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/5/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/5/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/5/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/5/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/5/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db5 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.5.socket --port 3005 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.5.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/6/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/6/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/6/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/6/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/6/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db6 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.6.socket --port 3006 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.6.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/7/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/7/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/7/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/7/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/7/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db7 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.7.socket --port 3007 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.7.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/8/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/8/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/8/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/8/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/8/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db8 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.8.socket --port 3008 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.8.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/9/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/9/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/9/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/9/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/9/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db9 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.9.socket --port 3009 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.9.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/10/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/10/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/10/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/10/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/10/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db10 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.10.socket --port 3010 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.10.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/11/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/11/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/11/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/11/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/11/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db11 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.11.socket --port 3011 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.11.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/12/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/12/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/12/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/12/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/12/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db12 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.12.socket --port 3012 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.12.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/13/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/13/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/13/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/13/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/13/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db13 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.13.socket --port 3013 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.13.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/14/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/14/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/14/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/14/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/14/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db14 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.14.socket --port 3014 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.14.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/15/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/15/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/15/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/15/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/15/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db15 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.15.socket --port 3015 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.15.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/16/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/16/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/16/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/16/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/16/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db16 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.16.socket --port 3016 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.16.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/17/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/17/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/17/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/17/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/17/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db17 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.17.socket --port 3017 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.17.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/18/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/18/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/18/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/18/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/18/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db18 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.18.socket --port 3018 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.18.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/19/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/19/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/19/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/19/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/19/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db19 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.19.socket --port 3019 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.19.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/20/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/20/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/20/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/20/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/20/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db20 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.20.socket --port 3020 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.20.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/21/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/21/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/21/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/21/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/21/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db21 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.21.socket --port 3021 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.21.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/22/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/22/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/22/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/22/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/22/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db22 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.22.socket --port 3022 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.22.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/23/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/23/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/23/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/23/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/23/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db23 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.23.socket --port 3023 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.23.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/24/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/24/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/24/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/24/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/24/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db24 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.24.socket --port 3024 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.24.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/25/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/25/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/25/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/25/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/25/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db25 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.25.socket --port 3025 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.25.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/26/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/26/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/26/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/26/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/26/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db26 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.26.socket --port 3026 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.26.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/27/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/27/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/27/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/27/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/27/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db27 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.27.socket --port 3027 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.27.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/28/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/28/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/28/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/28/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/28/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db28 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.28.socket --port 3028 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.28.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/29/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/29/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/29/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/29/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/29/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db29 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.29.socket --port 3029 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.29.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --shelley-kes-key /home/ubuntu/testnet-generation-tool/testnet/pools/30/keys/kes.skey --shelley-vrf-key /home/ubuntu/testnet-generation-tool/testnet/pools/30/keys/vrf.skey --shelley-operational-certificate /home/ubuntu/testnet-generation-tool/testnet/pools/30/keys/opcert.cert --config /home/ubuntu/testnet-generation-tool/testnet/pools/30/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/pools/30/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/deployment/db30 --socket-path /home/ubuntu/testnet-generation-tool/testnet/deployment/node.30.socket --port 3030 >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/deployment/pid.30.file
nohup /home/ubuntu/testnet-generation-tool/cardano-node/bin/cardano-node run --config /home/ubuntu/testnet-generation-tool/testnet/recovery/configs/config.json --topology /home/ubuntu/testnet-generation-tool/testnet/recovery/configs/topology.json --database-path /home/ubuntu/testnet-generation-tool/testnet/recovery/db --socket-path /home/ubuntu/testnet-generation-tool/testnet/recovery/node.socket >/dev/null 2>&1 &
echo $! >/home/ubuntu/testnet-generation-tool/testnet/recovery/pid.file
echo "Started 30 pool nodes ..." 
echo "Started recovery node ..." 
echo "monitoring: http://localhost:3000"