#TODO: setup configuration as needed
# Top-level configuration for Acropolis omnibus process

[module.genesis-bootstrapper]

[module.upstream-chain-fetcher]
sync-point = "snapshot"
node-address = "backbone.cardano.iog.io:3001"
magic-number = 764824073

[module.block-unpacker]

[module.tx-unpacker]
publish-utxo-deltas-topic = "cardano.utxo.deltas"
publish-certificates-topic = "cardano.certificates"
publish-governance-topic = "cardano.governance"
publish-fees-topic = "cardano.block.fees"

[module.utxo-state]
store = "memory"                              # "memory", "dashmap", "fjall", "fjall-async", "sled", "sled-async", "fake"
address-delta-topic = "cardano.address.delta"

[module.spo-state]

[module.drep-state]

[module.governance-state]

[module.parameters-state]

[module.stake-delta-filter]
cache-mode = "predefined"  # "predefined", "read", "write", "write-if-absent"
write-full-cache = "false"

[module.epoch-activity-counter]

[module.accounts-state]

[module.clock]

[module.rest-server]
address = "127.0.0.1"
port = 4340

[module.spy]
# Enable for message spying
#topic = "cardano.stake.deltas"

[startup]
topic = "cardano.sequence.start"

[message-bus.external]
class = "rabbit-mq"
url = "amqp://127.0.0.1:5672/%2f"
exchange = "caryatid"

[message-bus.internal]
class = "in-memory"
workers = 50
dispatch-queue-size = 1000
worker-queue-size = 100
bulk-block-capacity = 50
bulk-resume-capacity = 75

# Message routing
[[message-router.route]] # Everything is internal only
pattern = "#"
bus = "internal"
